DASHBOARD_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>EvidenceOps Fleet</title><style>
:root{color-scheme:dark;--bg:#07111f;--card:#0d1b2d;--line:#203750;--text:#eef6ff;--muted:#93a9bf;--cyan:#39d9c8;--amber:#ffca66;--red:#ff7b83}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#123252 0,transparent 35%),var(--bg);color:var(--text);font:15px/1.55 Inter,ui-sans-serif,system-ui,sans-serif}
main{max-width:1180px;margin:auto;padding:42px 22px 70px}.eyebrow{color:var(--cyan);font-weight:800;letter-spacing:.14em;text-transform:uppercase}.hero{display:grid;grid-template-columns:1.4fr .8fr;gap:28px;align-items:end;margin-bottom:30px}h1{font-size:clamp(42px,7vw,78px);line-height:.95;margin:10px 0 18px;letter-spacing:-.055em}.lede{max-width:700px;color:#bfd0df;font-size:18px}.badge{display:inline-flex;border:1px solid #2e5972;background:#0b2738;padding:8px 12px;border-radius:999px;color:#b9f7ef}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.card{background:linear-gradient(145deg,#10243a,#0a1727);border:1px solid var(--line);border-radius:20px;padding:22px;box-shadow:0 18px 45px #0005}h2{font-size:17px;margin:0 0 14px}label{display:block;color:var(--muted);font-size:13px;margin:13px 0 6px}select,textarea,input{width:100%;color:var(--text);background:#071522;border:1px solid #29445d;border-radius:10px;padding:11px;font:inherit}textarea{min-height:105px;resize:vertical}button{border:0;border-radius:11px;padding:12px 17px;background:var(--cyan);color:#04221f;font-weight:900;cursor:pointer;margin-top:16px}button:hover{filter:brightness(1.08)}pre{white-space:pre-wrap;word-break:break-word;background:#06101b;border-radius:12px;padding:16px;min-height:238px;color:#bcd0e1}.agents{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:20px 0}.agent{border-top:3px solid var(--cyan);background:#0b1a2a;padding:14px;border-radius:11px}.agent strong{display:block}.agent span{font-size:12px;color:var(--muted)}.status{font-weight:900;font-size:28px}.ready{color:var(--cyan)}.blocked{color:var(--red)}footer{margin-top:25px;color:var(--muted);font-size:13px}@media(max-width:800px){.hero,.grid{grid-template-columns:1fr}.agents{grid-template-columns:1fr 1fr}}
</style></head><body><main>
<section class="hero"><div><div class="eyebrow">Fortified Enterprise Fleet</div><h1>Evidence before action.</h1><p class="lede">A multi-agent control plane that catches missing or conflicting release evidence before publication, signing, payment, or deployment.</p></div><div><span class="badge">SYNTHETIC DEMO · NO PRIVATE DATA</span></div></section>
<section class="agents"><div class="agent"><strong>01 Intake</strong><span>Gemini 3.5 · source-bound facts</span></div><div class="agent"><strong>02 Policy</strong><span>Gemini 3.5 · deterministic tool</span></div><div class="agent"><strong>03 Verifier</strong><span>Canonical SHA-256 binding</span></div><div class="agent"><strong>04 Supervisor</strong><span>Gemini 3.5 · human boundary</span></div></section>
<section class="grid"><div class="card"><h2>Run an evidence case</h2><label for="scenario">Scenario</label><select id="scenario"><option value="ready">Complete release package</option><option value="missing">Missing test receipt</option><option value="conflict">Conflicting source commits</option></select><label for="objective">Bounded objective</label><input id="objective" value="Verify a release evidence package before publication"><label for="evidence">Source-attributed evidence</label><textarea id="evidence"></textarea><button id="run">Run specialist fleet</button></div>
<div class="card"><h2>Auditable outcome</h2><div id="decision" class="status">Not evaluated</div><pre id="result">Choose a scenario and run the fleet. The model cannot override deterministic missing/conflict checks.</pre></div></section>
<footer>Local mode uses an explicit in-memory store. Cloud Run + Firestore evidence will be published only after verified deployment.</footer>
</main><script>
const fixtures={ready:[{name:'commit',value:'abc123',source:'https://example.test/commit/abc123'},{name:'tests',value:'6 passed',source:'https://example.test/actions/100'},{name:'artifact',value:'sha256:0123456789abcdef',source:'https://example.test/releases/v1'}],missing:[{name:'commit',value:'abc123',source:'https://example.test/commit/abc123'},{name:'artifact',value:'sha256:0123456789abcdef',source:'https://example.test/releases/v1'}],conflict:[{name:'commit',value:'abc123',source:'https://example.test/commit/abc123'},{name:'commit',value:'def456',source:'https://mirror.example.test/commit/def456'},{name:'tests',value:'6 passed',source:'https://example.test/actions/100'},{name:'artifact',value:'sha256:0123456789abcdef',source:'https://example.test/releases/v1'}]};
const scenario=document.querySelector('#scenario'),evidence=document.querySelector('#evidence'),decision=document.querySelector('#decision'),result=document.querySelector('#result');function load(){evidence.value=JSON.stringify(fixtures[scenario.value],null,2)}scenario.onchange=load;load();document.querySelector('#run').onclick=async()=>{decision.textContent='Evaluating…';decision.className='status';try{const response=await fetch('/cases',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({case_id:`demo-${scenario.value}-${Date.now()}`,objective:document.querySelector('#objective').value,required_evidence:['commit','tests','artifact'],evidence:JSON.parse(evidence.value)})}),body=await response.json();if(!response.ok)throw new Error(body.detail||response.statusText);decision.textContent=body.decision.toUpperCase();decision.className=`status ${body.decision}`;result.textContent=JSON.stringify(body,null,2)}catch(error){decision.textContent='ERROR';decision.className='status blocked';result.textContent=error.message}};
</script></body></html>"""

